export const navData = [
  {
    id: 1,
    name: "Dashboard",
    href: "/",
    component: "HomePage",
  },
  {
    id: 2,
    name: "Schedule",
    href: "/schedule",
    component: "SchedulePage",
  },
  {
    id: 3,
    name: "Statistics",
    href: "/statistics",
    component: "StatisticsPage",
  },
  {
    id: 4,
    name: "Teams/Players",
    href: "/teams",
    component: "TeamsPage",
  },
  {
    id: 5,
    name: "About Us",
    href: "/about-us",
    component: "AboutUsPage",
  },
];

export const mlbbTeams = [
  {
    rank: 1,
    team: "Team Liquid",
    matches_played: 10,
    wins: 8,
    losses: 2,
    kills: 150,
    towers_destroyed: 50,
    gold_earned: 250000,
    mvp: 5,
    points: 24,
    href: "/teams/team-liquid.png",
  },
  {
    rank: 2,
    team: "Team Falcons",
    matches_played: 10,
    wins: 6,
    losses: 4,
    kills: 120,
    towers_destroyed: 40,
    gold_earned: 200000,
    mvp: 3,
    points: 18,
    href: "/teams/team-falcons.png",
  },
  {
    rank: 3,
    team: "Fnatic",
    matches_played: 10,
    wins: 5,
    losses: 5,
    kills: 100,
    towers_destroyed: 35,
    gold_earned: 180000,
    mvp: 2,
    points: 15,
    href: "/teams/fnatic.png",
  },
  {
    rank: 4,
    team: "Team Secret",
    matches_played: 10,
    wins: 4,
    losses: 6,
    kills: 90,
    towers_destroyed: 30,
    gold_earned: 160000,
    mvp: 1,
    points: 12,
    href: "/teams/team-secret.png",
  },
  {
    rank: 5,
    team: "Ninjas in Pyjamas",
    matches_played: 10,
    wins: 3,
    losses: 7,
    kills: 80,
    towers_destroyed: 25,
    gold_earned: 140000,
    mvp: 1,
    points: 9,
    href: "/teams/ninjas-in-pyjamas.png",
  },
  {
    rank: 6,
    team: "Twisted Minds",
    matches_played: 10,
    wins: 2,
    losses: 8,
    kills: 70,
    towers_destroyed: 20,
    gold_earned: 120000,
    mvp: 0,
    points: 6,
    href: "/teams/twisted-minds.png",
  },
  {
    rank: 7,
    team: "Optic Gaming",
    matches_played: 10,
    wins: 1,
    losses: 9,
    kills: 60,
    towers_destroyed: 15,
    gold_earned: 100000,
    mvp: 0,
    points: 3,
    href: "/teams/optic-gaming.png",
  },
  {
    rank: 8,
    team: "Cloud9",
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
    href: "/teams/cloud9.png",
  },
  {
    rank: 9,
    team: "OG",
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
    href: "/teams/og.png",
  },
  {
    rank: 10,
    team: "Evil Geniuses",
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
    href: "/teams/evil-geniuses.png",
  },
  {
    rank: 11,
    team: "Natus Vincere",
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
    href: "/teams/natus-vincere.png",
  },
];

export const valorantTeams = [
  {
    rank: 1,
    team: "Team Liquid",
    matches_played: 10,
    wins: 8,
    losses: 2,
    spike_plants: 150,
    defuses: 50,
    headshots: 100,
    points: 24,
    href: "/teams/team-liquid.png",
  },
  {
    rank: 2,
    team: "Team Falcons",
    matches_played: 10,
    wins: 6,
    losses: 4,
    spike_plants: 120,
    defuses: 40,
    headshots: 90,
    points: 18,
    href: "/teams/team-falcons.png",
  },
  {
    rank: 3,
    team: "Fnatic",
    matches_played: 10,
    wins: 5,
    losses: 5,
    spike_plants: 100,
    defuses: 35,
    headshots: 80,
    points: 15,
    href: "/teams/fnatic.png",
  },
  {
    rank: 4,
    team: "Team Secret",
    matches_played: 10,
    wins: 4,
    losses: 6,
    spike_plants: 90,
    defuses: 30,
    headshots: 70,
    points: 12,
    href: "/teams/team-secret.png",
  },
  {
    rank: 5,
    team: "Ninjas in Pyjamas",
    matches_played: 10,
    wins: 3,
    losses: 7,
    spike_plants: 80,
    defuses: 25,
    headshots: 60,
    points: 9,
    href: "/teams/ninjas-in-pyjamas.png",
  },
  {
    rank: 6,
    team: "Twisted Minds",
    matches_played: 10,
    wins: 2,
    losses: 8,
    spike_plants: 70,
    defuses: 20,
    headshots: 50,
    points: 6,
    href: "/teams/twisted-minds.png",
  },
  {
    rank: 7,
    team: "Optic Gaming",
    matches_played: 10,
    wins: 1,
    losses: 9,
    spike_plants: 60,
    defuses: 15,
    headshots: 40,
    points: 3,
    href: "/teams/optic-gaming.png",
  },
  {
    rank: 8,
    team: "Cloud9",
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 30,
    points: 0,
    href: "/teams/cloud9.png",
  },
  {
    rank: 9,
    team: "OG",
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 20,
    points: 0,
    href: "/teams/og.png",
  },
  {
    rank: 10,
    team: "Evil Geniuses",
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 10,
    points: 0,
    href: "/teams/evil-geniuses.png",
  },
  {
    rank: 11,
    team: "Natus Vincere",
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 5,
    points: 0,
    href: "/teams/natus-vincere.png",
  },
];

export const pubgTeams = [
  {
    rank: 1,
    team: "Team Liquid",
    matches_played: 10,
    chicken_dinners: 8,
    kill_points: 150,
    placement_points: 150,
    damage_dealt: 150,
    points: 24,
    href: "/teams/team-liquid.png",
  },
  {
    rank: 2,
    team: "Team Falcons",
    matches_played: 10,
    chicken_dinners: 6,
    kill_points: 120,
    placement_points: 120,
    damage_dealt: 120,
    points: 18,
    href: "/teams/team-falcons.png",
  },
  {
    rank: 3,
    team: "Fnatic",
    matches_played: 10,
    chicken_dinners: 5,
    kill_points: 100,
    placement_points: 100,
    damage_dealt: 100,
    points: 15,
    href: "/teams/fnatic.png",
  },
  {
    rank: 4,
    team: "Team Secret",
    matches_played: 10,
    chicken_dinners: 4,
    kill_points: 90,
    placement_points: 90,
    damage_dealt: 90,
    points: 12,
    href: "/teams/team-secret.png",
  },
  {
    rank: 5,
    team: "Ninjas in Pyjamas",
    matches_played: 10,
    chicken_dinners: 3,
    kill_points: 80,
    placement_points: 80,
    damage_dealt: 80,
    points: 9,
    href: "/teams/ninjas-in-pyjamas.png",
  },
  {
    rank: 6,
    team: "Twisted Minds",
    matches_played: 10,
    chicken_dinners: 2,
    kill_points: 70,
    placement_points: 70,
    damage_dealt: 70,
    points: 6,
    href: "/teams/twisted-minds.png",
  },
  {
    rank: 7,
    team: "Optic Gaming",
    matches_played: 10,
    chicken_dinners: 1,
    kill_points: 60,
    placement_points: 60,
    damage_dealt: 60,
    points: 3,
    href: "/teams/optic-gaming.png",
  },
  {
    rank: 8,
    team: "Cloud9",
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
    href: "/teams/cloud9.png",
  },
  {
    rank: 9,
    team: "OG",
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
    href: "/teams/og.png",
  },
  {
    rank: 10,
    team: "Evil Geniuses",
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
    href: "/teams/evil-geniuses.png",
  },
  {
    rank: 11,
    team: "Natus Vincere",
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
    href: "/teams/natus-vincere.png",
  },
];

export const mlbbHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Wins",
  "Losses",
  "Kills",
  "Towers Destroyed",
  "Points",
];

export const valorantHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Wins",
  "Losses",
  "Spike Plants",
  "Defuses",
  "Headshots",
  "Points",
];

export const pubgHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Chicken Dinners",
  "Kill Points",
  "Placement Points",
  "Damage Dealt",
  "Points",
];
