export const navData = [
  {
    id: 1,
    name: "Home Page",
    href: "/",
    component: "HomePage",
  },
  {
    id: 2,
    name: "Schedule",
    href: "/schedule",
    component: "SchedulePage",
  },
  {
    id: 3,
    name: "Statistics",
    href: "/statistics",
    component: "StatisticsPage",
  },
  {
    id: 4,
    name: "Teams/Players",
    href: "/teams",
    component: "TeamsPage",
  },
  {
    id: 5,
    name: "About Us",
    href: "/about-us",
    component: "AboutUsPage",
  },
];

export const teamsData = [
  {
    id: 1,
    name: "Team Liquid",
    shortName: "TL",
    href: "/teams/team-liquid.png",
    membersPicture: "/team_mem/TL-GP.jpeg",
  },
  {
    id: 2,
    name: "Team Falcons",
    shortName: "TF",
    href: "/teams/team-falcons.png",
    membersPicture: "/team_mem/TF.jpg",
  },
  {
    id: 3,
    name: "Fnatic",
    shortName: "FNC",
    href: "/teams/fnatic.png",
    membersPicture: "/team_mem/FT.jpeg",
  },
  {
    id: 4,
    name: "Team Secret",
    shortName: "TS",
    href: "/teams/team-secret.png",
    membersPicture: "/team_mem/TS.jpeg",
  },
  {
    id: 5,
    name: "Ninjas in Pyjamas",
    shortName: "NIP",
    href: "/teams/ninjas-in-pyjamas.png",
    membersPicture: "/team_mem/NIP.jpg",
  },
  {
    id: 6,
    name: "Twisted Minds",
    shortName: "TM",
    href: "/teams/twisted-minds.png",
    membersPicture: "/team_mem/tm.jpg",
  },
  {
    id: 7,
    name: "Optic Gaming",
    shortName: "OG",
    href: "/teams/optic-gaming.png",
    membersPicture: "/team_mem/og.jpg",
  },
  {
    id: 8,
    name: "Cloud9",
    shortName: "C9",
    href: "/teams/cloud9.png",
    membersPicture: "/team_mem/C9.jpeg",
  },
  {
    id: 9,
    name: "OG",
    shortName: "OG",
    href: "/teams/og.png",
    membersPicture: "/team_mem/og.jpg",
  },
  {
    id: 10,
    name: "Evil Geniuses",
    shortName: "EG",
    href: "/teams/evil-geniuses.png",
    membersPicture: "/team_mem/EG.jpeg",
  },
  {
    id: 11,
    name: "Natus Vincere",
    shortName: "NAVI",
    href: "/teams/natus-vincere.png",
    membersPicture: "/team_mem/NV.jpg",
  },
];

export const mlbbTeams = [
  {
    rank: 1,
    team: 1,
    matches_played: 10,
    wins: 8,
    losses: 2,
    kills: 150,
    towers_destroyed: 50,
    gold_earned: 250000,
    mvp: 5,
    points: 24,
  },
  {
    rank: 2,
    team: 2,
    matches_played: 10,
    wins: 6,
    losses: 4,
    kills: 120,
    towers_destroyed: 40,
    gold_earned: 200000,
    mvp: 3,
    points: 18,
  },
  {
    rank: 3,
    team: 3,
    matches_played: 10,
    wins: 5,
    losses: 5,
    kills: 100,
    towers_destroyed: 35,
    gold_earned: 180000,
    mvp: 2,
    points: 15,
  },
  {
    rank: 4,
    team: 4,
    matches_played: 10,
    wins: 4,
    losses: 6,
    kills: 90,
    towers_destroyed: 30,
    gold_earned: 160000,
    mvp: 1,
    points: 12,
  },
  {
    rank: 5,
    team: 5,
    matches_played: 10,
    wins: 3,
    losses: 7,
    kills: 80,
    towers_destroyed: 25,
    gold_earned: 140000,
    mvp: 1,
    points: 9,
  },
  {
    rank: 6,
    team: 6,
    matches_played: 10,
    wins: 2,
    losses: 8,
    kills: 70,
    towers_destroyed: 20,
    gold_earned: 120000,
    mvp: 0,
    points: 6,
  },
  {
    rank: 7,
    team: 7,
    matches_played: 10,
    wins: 1,
    losses: 9,
    kills: 60,
    towers_destroyed: 15,
    gold_earned: 100000,
    mvp: 0,
    points: 3,
  },
  {
    rank: 8,
    team: 8,
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
  },
  {
    rank: 9,
    team: 9,
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
  },
  {
    rank: 10,
    team: 10,
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
  },
  {
    rank: 11,
    team: 11,
    matches_played: 10,
    wins: 0,
    losses: 10,
    kills: 50,
    towers_destroyed: 10,
    gold_earned: 80000,
    mvp: 0,
    points: 0,
  },
];

export const valorantTeams = [
  {
    rank: 1,
    team: 1,
    matches_played: 10,
    wins: 8,
    losses: 2,
    spike_plants: 150,
    defuses: 50,
    headshots: 100,
    points: 24,
  },
  {
    rank: 2,
    team: 2,
    matches_played: 10,
    wins: 6,
    losses: 4,
    spike_plants: 120,
    defuses: 40,
    headshots: 90,
    points: 18,
  },
  {
    rank: 3,
    team: 3,
    matches_played: 10,
    wins: 5,
    losses: 5,
    spike_plants: 100,
    defuses: 35,
    headshots: 80,
    points: 15,
  },
  {
    rank: 4,
    team: 4,
    matches_played: 10,
    wins: 4,
    losses: 6,
    spike_plants: 90,
    defuses: 30,
    headshots: 70,
    points: 12,
  },
  {
    rank: 5,
    team: 5,
    matches_played: 10,
    wins: 3,
    losses: 7,
    spike_plants: 80,
    defuses: 25,
    headshots: 60,
    points: 9,
  },
  {
    rank: 6,
    team: 6,
    matches_played: 10,
    wins: 2,
    losses: 8,
    spike_plants: 70,
    defuses: 20,
    headshots: 50,
    points: 6,
  },
  {
    rank: 7,
    team: 7,
    matches_played: 10,
    wins: 1,
    losses: 9,
    spike_plants: 60,
    defuses: 15,
    headshots: 40,
    points: 3,
  },
  {
    rank: 8,
    team: 8,
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 30,
    points: 0,
  },
  {
    rank: 9,
    team: 9,
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 20,
    points: 0,
  },
  {
    rank: 10,
    team: 10,
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 10,
    points: 0,
  },
  {
    rank: 11,
    team: 11,
    matches_played: 10,
    wins: 0,
    losses: 10,
    spike_plants: 50,
    defuses: 10,
    headshots: 5,
    points: 0,
  },
];

export const pubgTeams = [
  {
    rank: 1,
    team: 1,
    matches_played: 10,
    chicken_dinners: 8,
    kill_points: 150,
    placement_points: 150,
    damage_dealt: 150,
    points: 24,
  },
  {
    rank: 2,
    team: 2,
    matches_played: 10,
    chicken_dinners: 6,
    kill_points: 120,
    placement_points: 120,
    damage_dealt: 120,
    points: 18,
  },
  {
    rank: 3,
    team: 3,
    matches_played: 10,
    chicken_dinners: 5,
    kill_points: 100,
    placement_points: 100,
    damage_dealt: 100,
    points: 15,
  },
  {
    rank: 4,
    team: 4,
    matches_played: 10,
    chicken_dinners: 4,
    kill_points: 90,
    placement_points: 90,
    damage_dealt: 90,
    points: 12,
  },
  {
    rank: 5,
    team: 5,
    matches_played: 10,
    chicken_dinners: 3,
    kill_points: 80,
    placement_points: 80,
    damage_dealt: 80,
    points: 9,
  },
  {
    rank: 6,
    team: 6,
    matches_played: 10,
    chicken_dinners: 2,
    kill_points: 70,
    placement_points: 70,
    damage_dealt: 70,
    points: 6,
  },
  {
    rank: 7,
    team: 7,
    matches_played: 10,
    chicken_dinners: 1,
    kill_points: 60,
    placement_points: 60,
    damage_dealt: 60,
    points: 3,
  },
  {
    rank: 8,
    team: 8,
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
  },
  {
    rank: 9,
    team: 9,
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
  },
  {
    rank: 10,
    team: 10,
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
  },
  {
    rank: 11,
    team: 11,
    matches_played: 10,
    chicken_dinners: 0,
    kill_points: 50,
    placement_points: 50,
    damage_dealt: 50,
    points: 0,
  },
];

export const mlbbHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Wins",
  "Losses",
  "Kills",
  "Towers Destroyed",
  "Points",
];

export const valorantHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Wins",
  "Losses",
  "Spike Plants",
  "Defuses",
  "Headshots",
  "Points",
];

export const pubgHeaders = [
  "Rank",
  "Team",
  "Matches Played",
  "Chicken Dinners",
  "Kill Points",
  "Placement Points",
  "Damage Dealt",
  "Points",
];

export const matchSchedule = [
  {
    id: 11,
    datetime: "2024-11-24T14:00:00",
    game: "valorant",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 1, result: 1 },
      { id: 2, result: 0 },
    ],
  },
  {
    id: 12,
    datetime: "2024-11-24T15:00:00",
    game: "valorant",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 3, result: 0 },
      { id: 4, result: 1 },
    ],
  },
  {
    id: 13,
    datetime: "2024-11-24T16:00:00",
    game: "valorant",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 5, result: 1 },
      { id: 6, result: 0 },
    ],
  },
  {
    id: 14,
    datetime: "2024-11-24T17:00:00",
    game: "valorant",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 7, result: 0 },
      { id: 8, result: 1 },
    ],
  },
  {
    id: 15,
    datetime: "2024-11-24T18:00:00",
    game: "valorant",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 9, result: 1 },
      { id: 10, result: 0 },
    ],
  },
  {
    id: 16,
    datetime: "2024-11-25T14:00:00",
    game: "pubg",
    stage: "Quarter Finals",
    bo: 3,
    duration: "1h 30m",
    location: "Main Auditorium, University Hall",
    teams: [
      { id: 1, result: 1 },
      { id: 2, result: 2 },
    ],
  },
  {
    id: 17,
    datetime: "2024-11-25T16:00:00",
    game: "pubg",
    stage: "Quarter Finals",
    bo: 3,
    duration: "1h 20m",
    location: "Main Auditorium, University Hall",
    teams: [
      { id: 3, result: null },
      { id: 4, result: null },
    ],
  },
  {
    id: 18,
    datetime: "2024-11-26T14:00:00",
    game: "pubg",
    stage: "Semi Finals",
    bo: 5,
    duration: null,
    location: "E-Sports Arena, University Hall",
    teams: [
      { id: 5, result: null },
      { id: 6, result: null },
    ],
  },
  {
    id: 19,
    datetime: "2024-11-26T16:00:00",
    game: "pubg",
    stage: "Semi Finals",
    bo: 5,
    duration: "2h",
    location: "E-Sports Arena, University Hall",
    teams: [
      { id: 7, result: null },
      { id: 8, result: null },
    ],
  },
  {
    id: 20,
    datetime: "2024-11-27T14:00:00",
    game: "pubg",
    stage: "Finals",
    bo: 7,
    duration: "3h",
    location: "Grand Stadium, University Hall",
    teams: [
      { id: 9, result: null },
      { id: 10, result: null },
    ],
  },
  {
    id: 6,
    datetime: "2024-11-24T14:00:00",
    game: "mlbb",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 1, result: 0 },
      { id: 3, result: 1 },
    ],
  },
  {
    id: 7,
    datetime: "2024-11-24T15:00:00",
    game: "mlbb",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 2, result: 1 },
      { id: 4, result: 0 },
    ],
  },
  {
    id: 8,
    datetime: "2024-11-24T16:00:00",
    game: "mlbb",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 5, result: 1 },
      { id: 6, result: 0 },
    ],
  },
  {
    id: 9,
    datetime: "2024-11-24T17:00:00",
    game: "mlbb",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 7, result: 0 },
      { id: 8, result: 1 },
    ],
  },
  {
    id: 10,
    datetime: "2024-11-24T18:00:00",
    game: "mlbb",
    stage: "Group Stage",
    bo: 1,
    duration: "45m",
    location: "Training Room, University Hall",
    teams: [
      { id: 9, result: 1 },
      { id: 10, result: 0 },
    ],
  },
  {
    id: 1,
    datetime: "2024-11-25T14:00:00",
    game: "mlbb",
    stage: "Quarter Finals",
    bo: 3,
    duration: "1h 30m",
    location: "Main Auditorium, University Hall",
    teams: [
      { id: 1, result: 1 },
      { id: 2, result: 2 },
    ],
  },
  {
    id: 2,
    datetime: "2024-11-25T16:00:00",
    game: "mlbb",
    stage: "Quarter Finals",
    bo: 3,
    duration: "1h 20m",
    location: "Main Auditorium, University Hall",
    teams: [
      { id: 4, result: null },
      { id: 3, result: null },
    ],
  },
  {
    id: 3,
    datetime: "2024-11-26T14:00:00",
    game: "mlbb",
    stage: "Semi Finals",
    bo: 5,
    duration: null,
    location: "E-Sports Arena, University Hall",
    teams: [
      { id: 6, result: null },
      { id: 7, result: null },
    ],
  },
  {
    id: 4,
    datetime: "2024-11-26T16:00:00",
    game: "mlbb",
    stage: "Semi Finals",
    bo: 5,
    duration: "2h",
    location: "E-Sports Arena, University Hall",
    teams: [
      { id: 8, result: null },
      { id: 9, result: null },
    ],
  },
  {
    id: 5,
    datetime: "2024-11-27T14:00:00",
    game: "mlbb",
    stage: "Finals",
    bo: 7,
    duration: "3h",
    location: "Grand Stadium, University Hall",
    teams: [
      { id: 10, result: null },
      { id: 11, result: null },
    ],
  },
];

export const playersData = [
  // Players for Mobile Legends: Bang Bang (MLBB)
  {
    id: 1,
    name: "Player One",
    teamId: 1, // Refers to Team Liquid
    game: "MLBB",
    kills: 80,
    assists: 40,
    deaths: 20,
    towers_destroyed: 15,
    gold_earned: 75000,
    mvp: 3,
  },
  {
    id: 2,
    name: "Player Two",
    teamId: 1, // Refers to Team Liquid
    game: "MLBB",
    kills: 70,
    assists: 45,
    deaths: 30,
    towers_destroyed: 10,
    gold_earned: 70000,
    mvp: 2,
  },
  {
    id: 3,
    name: "Player Three",
    teamId: 2, // Refers to Team Falcons
    game: "MLBB",
    kills: 60,
    assists: 50,
    deaths: 25,
    towers_destroyed: 8,
    gold_earned: 65000,
    mvp: 1,
  },

  // Players for Valorant
  {
    id: 4,
    name: "Agent Zero",
    teamId: 3, // Refers to Fnatic
    game: "Valorant",
    kills: 200,
    headshots: 60,
    deaths: 50,
    spike_plants: 30,
    defuses: 15,
    mvp: 4,
  },
  {
    id: 5,
    name: "Agent One",
    teamId: 4, // Refers to Team Secret
    game: "Valorant",
    kills: 180,
    headshots: 55,
    deaths: 60,
    spike_plants: 25,
    defuses: 20,
    mvp: 3,
  },

  // Players for PUBG
  {
    id: 6,
    name: "Sniper Pro",
    teamId: 5, // Refers to Ninjas in Pyjamas
    game: "PUBG",
    kills: 100,
    damage_dealt: 1500,
    knockdowns: 20,
    headshots: 30,
    survival_time: "30m",
    chicken_dinners: 4,
    mvp: 2,
  },
  {
    id: 7,
    name: "Assault King",
    teamId: 6, // Refers to Twisted Minds
    game: "PUBG",
    kills: 120,
    damage_dealt: 2000,
    knockdowns: 25,
    headshots: 40,
    survival_time: "35m",
    chicken_dinners: 5,
    mvp: 3,
  },
];

export const matchScheduleForm = {
  datetime: "",
  game: "",
  stage: "",
  bo: "",
  duration: "",
  location: "",
  teams: [
    { id: 0, result: 0 },
    { id: 0, result: 0 },
  ],
};
